---
swagger:
  api_url: /static/swagger.yaml
  ui_url: /api/docs

ldap_servers:
  mocked:
    ldap_host: localhost
    server_config:
      port: 389
      use_ssl: False
    connection_config:
      user: n=admin,dc=test,dc=lab
      client_strategy: MOCK_SYNC

  test:
    ldap_host: 192.168.1.5
    server_config:
      port: 389
      use_ssl: False
    connection_config:
      user: "cn=admin,dc=test,dc=lab"
      authentication: SIMPLE
      auto_bind: AUTO_BIND_NO_TLS
