--- 
swagger: 
  api_url: /static/swagger.yaml
  ui_url: /api/docs

ldap:
  connection_default_default:
    # https://ldap3/readthedocs/io/en/latest/connection/html
    auto_bind: AUTO_BIND_NONE
    version: 3
    authentication: AUTH_SIMPLE
    client_strategy: REUSABLE
    auto_referrals: True
    sasl_mechanism: None
    sasl_credential: None
    collect_usage: True
    read_only: False
    lazy: True
    check_names: True
    raise_exceptions: False
    pool_name: default
    pool_size: 5
    pool_lifetime: 120
    pool_keepalive: 0
    fast_decoder: True
    receive_timeout: 20
    return_empty_attributes: True
    auto_range: True
    use_referral_cache: True
    auto_escape: True
    auto_encode: True

  server_default_config:
    allowed_referral_hosts: None
    get_info: SCHEMA
    mode: IP_SYSTEM_DEFAULT
    tls: None
    formatter: None

  local:
    server_config:
      # See https://ldap3.readthedocs.io/en/latest/server.html#
      ldap_host: 192.168.1.5
      user: admin
      password: <<PASSWORD_PLACEHOLDER>>
      ldap_port: 389
      use_ssl: False
    connection_config:
      pool_name: local
      fast_decoder: False

  mocked:
    server_config:
      # See https://ldap3.readthedocs.io/en/latest/server.html#
      ldap_host: 192.168.1.5
      user: admin
      password: <<PASSWORD_PLACEHOLDER>>
      ldap_port: 389
      use_ssl: False
      check_names: False
    connection_config:
      client_strategy: MOCK_SYNC
      authentication: ANONYMOUS
      pool_name: mocked
      pool_size: 1
      fast_decoder: False

    server_pool_config:
      ha_active: True
      ha_exhust: 1200
      ha_strategy: ROUND_ROBIN
      ldap_timeout:
      ldap_debug:
      pool_name: Config.get(LDAP)['pool_name']
      pool_size: int(Config.get(LDAP)['pool_size'])
      pool_lifetime: int(Config.get(LDAP)['pool_lifetime'])
      pool_keepalive: int(Config.get(LDAP)['pool_keepalive'])
      ldap_use_ssl: Config.get(LDAP)['use_ssl']
      ldap3_log_level_str: Config.get(LDAP)['ldap3_log_level']
      ldap3_log_level : 0
