---
swagger:
  api_url: /static/swagger.yaml
  ui_url: /api/docs

ldap_servers:
  mocked:
    description: In memory LDAP Server
    ldap_host: ldap://localhost
    server_config:
      port: 389
    connection_config:
      user: cn=admin,dc=byteworksinc,dc=com
      client_strategy: MOCK_SYNC

  test:
    description: Local OpenLDAP server
    ldap_host: ldap://192.168.1.5
    server_config:
      connect_timeout: 360
      get_info: ALL
      port: 389
      use_ssl: True
    connection_config:
      authentication: SIMPLE
      auto_bind: AUTO_BIND_TLS_BEFORE_BIND
      auto_referrals: True
      client_strategy: SYNC
      user: cn=admin,dc=byteworksinc,dc=com
